name: tfm-amr
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - numpy
  - pandas
  - pyarrow         
  - scikit-learn
  - matplotlib
  - seaborn
  - biopython
  - jupyterlab
  - ipykernel
  - abricate         
  - mlst            
  - ncbi-datasets-cli
